mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除字段值
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
  type-handlers-package: com.example.demo.config

park:
  boundary:
    southwest:
      latitude: 30.145958
      longitude: 119.979967
    northeast:
      latitude: 30.159581
      longitude: 119.990873

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true